/*유저 테이블*/
CREATE TABLE GYU_SYS_USER
(
        USER_ID SERIAL PRIMARY KEY,
        USER_NM VARCHAR(50) NOT NULL,
        PASSWORD VARCHAR(200) NOT NULL,
        NAME VARCHAR(30) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL,
        PHONE VARCHAR(20) NOT NULL,
        ADDR_NO VARCHAR(50) NOT NULL,
        ADDR VARCHAR(300) NOT NULL,
        ADDR_DTL VARCHAR(500) NOT NULL,
        SEX_CD CHAR(1) NOT NULL,
        PWD_YN CHAR(1) NOT NULL,
        PWD_DATE DATE,
        LOGIN_DATE DATE,
        JOIN_TYPE VARCHAR(50) NOT NULL,
        API_KEY VARCHAR(200) NOT NULL
);
/*브랜드 테이블*/
CREATE TABLE GYU_SYS_BRAND
(
    BRAND_CD SERIAL PRIMARY KEY,
    BRAND_NM VARCHAR(50) NOT NULL,
    BRAND_IMG VARCHAR(100) NOT NULL,
    BRAND_ADDR_NO VARCHAR(50) NOT NULL,
    BRAND_ADDR VARCHAR(300) NOT NULL,
    BRAND_ADDR_DTL VARCHAR(500) NOT NULL,
    DELI_COMP_CD VARCHAR(30) NOT NULL,
    STATE_CD CHAR NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    NOTE VARCHAR(300)
);
/*권한 관리 테이블*/
CREATE TABLE GYU_SYS_ROLE
(
    ROLE_CD VARCHAR(30),
    ROLE_NM VARCHAR(50),
    NOTE VARCHAR(500),
    CONSTRAINT GYU_SYS_ROLE_PK PRIMARY KEY (ROLE_CD, ROLE_NM)
);
/*권한 종류*/
INSERT INTO GYU_SYS_ROLE VALUES('ROLE_ADMIN', 'ROLE_ADMIN','');
INSERT INTO GYU_SYS_ROLE VALUES('ROLE_USER', 'ROLE_USER','');
INSERT INTO GYU_SYS_ROLE VALUES('ROLE_BRAND', 'ROLE_BRAND','');

/*유저 권한 매핑 테이블*/
CREATE TABLE GYU_SYS_ROLE_USER
(
    USER_NM VARCHAR(50),
    ROLE_CD VARCHAR(50),
    START_DATE DATE,
    END_DATE DATE,
    BRAND_CD INTEGER,
    NOTE VARCHAR(300),
    CONSTRAINT GYU_SYS_ROLE_USER_PK PRIMARY KEY (USER_NM, ROLE_CD, START_DATE)
);